/**
 * define link-layer error code
 *
 */
#ifndef _BLE_LL_ERR_H_
#define _BLE_LL_ERR_H_

#include "les_if/api/inc/les_def.h"

#define BLE_LL_ERR_NUM  0x20

typedef enum {
    BLE_LL_ERR_HCI_UNKNOWN_INDICATOR = ERR_CONTROLLER,
    BLE_LL_ERR_INFORMATION_NOT_AVAILABLE,
    BLE_LL_ERR_NOT_PROCESSED_CMD,
    BLE_LL_ERR_HARDWARE_LOCKUP,
    BLE_LL_ERR_LPRAM_RECOVERY_FAIL,
    BLE_LL_ERR_UNKNOWN_OP_TYPE,
    BLE_LL_ERR_INSUFFICIENT_BANDWIDTH,
    BLE_LL_ERR_SLAVE_UNDEF_STATE,
    BLE_LL_ERR_MASTER_UNDEF_STATE,
    BLE_LL_ERR_INITA_UNDEF_STATE,
    BLE_LL_ERR_RANGE,
}   BLE_LL_ERR;

#endif // _BLE_LL_ERR_H_
