#ifndef _APPL_ERROR_H_
#define _APPL_ERROR_H_


#include <stdint.h>



typedef enum {

    APPL_RESULT_SUCCESS = 0,
    APPL_RESULT_FAIL,
    APPL_RESULT_NO_HANDLER_RESOURCE,
    APPL_RESULT_INVALID_HANDLER,

    APPL_RESULT_QUEUE_EMPTY,
    APPL_RESULT_QUEUE_FULL,
    APPL_RESULT_INVALID_SIZE,
    APPL_RESULT_INSUFFICIENT_MEMORY,

    APPL_RESULT_NO_AVAILABLE_ENTRY,

    APPL_RESULT_NOT_IMPLEMENT_YET,

} APPL_RESULT;



#endif  /// end of _APPL_ERROR_H_
