#ifndef _GATTC_DEF_H_
#define _GATTC_DEF_H_


#include "host_def.h"
#include "att/att_def.h"
#include "l2cap/l2cap_def.h"



#define GATTC_INVALID_CONNECTION_HANDLE         0xFFFF
#define GATTC_INVALID_ATTR_HANDLE               0x0000
#define GATTC_ATTR_HANDLE_MAX                   0xFFFF
#define GATTC_PROC_TIMEOUT                      30000


typedef enum
{
    GATTC_RESULT_SUCCESS = ERR_HOST_SUCCESS,
    GATTC_RESULT_FAIL = ERR_HOST_FAIL,
    GATTC_RESULT_INVALID_PARAM = ERR_HOST_INVALID_PARAM,
    GATTC_RESULT_INVALID_OPERATION = ERR_HOST_INVALID_OPERATION,
    GATTC_RESULT_INSUFF_RESOURCE = ERR_HOST_INSUFF_RESOURCE,
    GATTC_RESULT_TIMEOUT = ERR_HOST_TIMEOUT,
    GATTC_RESULT_DISCONNECT = ERR_HOST_DISCONNECT,
    GATTC_RESULT_INVALID_CONNECTION = ERR_HOST_INVALID_CONNECTION,

    GATTC_RESULT_MIN = ERR_HOST_GATTC,
    GATTC_RESULT_MAX,

} GATTC_RESULT;



#endif  /// end of _GATTC_DEF_H_
