
LIB_SRC := 

LIB_ASRC :=
LIBRARY_NAME := no
LOCAL_CFLAGS :=
LOCAL_AFLAGS :=

RELEASE_SRC := 1

$(eval $(call link-lib,$(LIBRARY_NAME),$(LIB_SRC),$(LIB_ASRC),$(LOCAL_CFLAGS),$(LOCAL_INC),$(LOCAL_AFLAGS),$(MYDIR)))
