#ifndef _BLE_HARDFAULT_H_
#define _BLE_HARDFAULT_H_

#include "les_if/api/inc/les_def.h"

typedef enum {

    // ########################################
    // # hardfault in LL
    // ########################################
    BLE_HARDFAULT_HCI_ACL_TX_LENGTH_ERROR = HARDFAULT_CONTROLLER,
    BLE_HARDFAULT_HCI_ADATA_OVERFLOW,
    BLE_HARDFAULT_HCI_EVT_OVERFLOW,
    BLE_HARDFAULT_HCI_CMD_OVERFLOW,
    BLE_HARDFAULT_HCI_ACL_OVERFLOW,
    BLE_HARDFAULT_LES_EVT_SEND_FAIL,
    BLE_HARDFAULT_PDU_FREE_FAIL,
    BLE_HARDFAULT_LL_MSG_SEND_FAIL,
    BLE_HARDFAULT_LLCP_PALLOC_FAIL,
    BLE_HARDFAULT_ADVDIRECT_FAKE_CONN_REQ_ALLOC_FAIL,
    BLE_HARDFAULT_SLAVE_LLCP_HOOKUP_ERROR,
    BLE_HARDFAULT_MASTER_LLCP_HOOKUP_ERROR,
    BLE_HARDFAULT_SLAVE_STATE_BUF_ALLOC_FAIL,
    BLE_HARDFAULT_LL_RX_HASH_UNEXPECTED_BEHAVIOR,
    BLE_HARDFAULT_LL_RX_RING_INITIALIZATION_FAIL,
    BLE_HARDFAULT_LL_AIR_EVENT_END_UNKNOWN_REASON,
    BLE_HARDFAULT_LL_AIR_EVENT_END_RX_STORE_TOUT,
    BLE_HARDFAULT_LL_AIR_EVENT_INVALID_ACCESS_TIME,
    BLE_HARDFAULT_LL_ANCHOR_STORE_FAIL,
    BLE_HARDFAULT_LL_ANCHOR_OFF_FAIL,
    BLE_HARDFAULT_LL_AIR_EVENT_NOTIFY_EXCEPTION,
    BLE_HARDFAULT_LL_DIRECT_HARD_END_FAIL,

    // ########################################
    // # hardfault in HOST
    // ########################################

    // ########################################
    // # hardfault in BSP
    // ########################################

} BLE_HARDFAULT;

#endif // _BLE_HARDFAULT_H_
