#ifndef _GATTS_DEF_H_
#define _GATTS_DEF_H_


#include "host_def.h"



#define GATTS_INVALID_CONNECTION_HANDLE         0xFFFF
#define GATTS_INVALID_ATTR_HANDLE               0x0000



typedef enum
{
    GATTS_RESULT_SUCCESS = ERR_HOST_SUCCESS,
    GATTS_RESULT_FAIL = ERR_HOST_FAIL,
    GATTS_RESULT_INVALID_PARAM = ERR_HOST_INVALID_PARAM,
    GATTS_RESULT_INVALID_OPERATION = ERR_HOST_INVALID_OPERATION,
    GATTS_RESULT_INSUFF_RESOURCE = ERR_HOST_INSUFF_RESOURCE,
    GATTS_RESULT_TIMEOUT = ERR_HOST_TIMEOUT,
    GATTS_RESULT_DISCONNECT = ERR_HOST_DISCONNECT,
    GATTS_RESULT_INVALID_CONNECTION = ERR_HOST_INVALID_CONNECTION,

    GATTS_RESULT_MIN = ERR_HOST_GATTS,
    GATTS_RESULT_MAX,

} GATTS_RESULT;



#endif  /// end of _GATTS_DEF_H_
