#ifndef _HCI_CONFIG_H_
#define _HCI_CONFIG_H_

/**
 * select HCI cmd group
 *
 */
#define _HCI_SUPPORT_CMD_NOP_
#define _HCI_SUPPORT_CMD_LINK_CONTROL_
#define _HCI_SUPPORT_CMD_CONTROL_BASEBAND_
#define _HCI_SUPPORT_CMD_INFORMATION_PARAMETERS_
#define _HCI_SUPPORT_CMD_STATUS_PARAMETERS_
#define _HCI_SUPPORT_CMD_LE_CONTROLLER_
#define _HCI_SUPPORT_CMD_SSV_CMD_

#endif // _HCI_CONFIG_H_
